const projects=[{id:"portfolio",title:"Personal portfolio",category:"frontend",status:"Live",image:"images/portfolio.svg",summary:"This site. A one-page freelance portfolio with project filters, services, and a working contact form.",problem:"Needed one page a client can scan on a phone and use to get in touch.",role:"Design, layout, and the contact flow.",outcome:"Live on Vercel, with work, services, and a form that confirms on send.",stack:["HTML","CSS","JavaScript"],liveUrl:"https://benjamin-osahon.vercel.app",repoUrl:"https://github.com/osascodes/osascodes.github.io"},{id:"meridian",title:"Meridian",category:"frontend",status:"In progress",image:"images/propertyhub.svg",summary:"A Lagos real-estate site for listings, developments, locations, and enquiries. Built as PropertyHub, branded Meridian.",problem:"Agencies need a clear catalog clients can browse, not a PDF of houses.",role:"Frontend: pages, layout, and the enquiry path.",outcome:"A company site for properties and enquiries. Demo link coming.",stack:["Next.js","React","TypeScript","Tailwind CSS"],repoUrl:"https://github.com/osascodes/propertyhub"},{id:"nova",title:"Nova Store",category:"fullstack",status:"In progress",image:"images/nova-store.svg",summary:"An ecommerce demo with catalog, cart, checkout, accounts, and an admin panel.",problem:"A store brief that needs products, orders, and login, not a static catalog.",role:"Full-stack: catalog, cart, checkout, auth, and admin.",outcome:"Orders and products persist in Postgres. Demo link coming.",stack:["Next.js","React","TypeScript","Node.js","Prisma","PostgreSQL","Tailwind CSS"],repoUrl:"https://github.com/osascodes/nova-store"},{id:"bizflow",title:"BizFlow",category:"fullstack",status:"In progress",image:"images/bizflow.svg",summary:"A mobile-first business tool for inventory, sales, receipts, customers, and WhatsApp checkout.",problem:"Small vendors run the shop from a phone and lose track of stock and debt.",role:"Product build across the app, auth, and data.",outcome:"In build on Next.js and Supabase. Demo link coming.",stack:["Next.js","React","TypeScript","Node.js","Supabase","Tailwind CSS","Zod"],repoUrl:"https://github.com/osascodes/bizflow"}];
const grid=document.getElementById("grid");const count=document.getElementById("count");const modal=document.getElementById("modal");const menu=document.getElementById("menu");const navLinks=document.getElementById("nav-links");let filter="all";const dirs=["fade-up","fade-down","fade-left","fade-right"];
function list(){return filter==="all"?projects:projects.filter(p=>p.category===filter)}
function render(){const items=list();count.textContent=items.length+(items.length===1?" project":" projects");grid.innerHTML=items.map((p,i)=>'<button class="card" data-id="'+p.id+'" data-aos="'+dirs[i%dirs.length]+'"><div class="thumb"><img src="'+p.image+'" alt="'+p.title+' preview"><span class="badge">'+(p.category==="fullstack"?"Full stack":"Frontend")+'</span></div><div class="card-body"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h3>'+p.title+'</h3><span class="status">'+p.status+'</span></div><p>'+p.summary+'</p><p class="more">View project →</p></div></button>').join("");if(window.AOS)AOS.refresh()}
function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;document.getElementById("m-tag").textContent=(p.category==="fullstack"?"Full stack":"Frontend")+" · "+p.status;document.getElementById("m-title").textContent=p.title;document.getElementById("m-summary").textContent=p.summary;document.getElementById("m-problem").textContent=p.problem;document.getElementById("m-role").textContent=p.role;document.getElementById("m-outcome").textContent=p.outcome;document.getElementById("m-stack").innerHTML=p.stack.map(s=>"<span>"+s+"</span>").join("");const img=document.getElementById("m-image");img.src=p.image;img.alt=p.title;img.hidden=false;const links=[];if(p.liveUrl)links.push('<a class="btn btn-solid" href="'+p.liveUrl+'" target="_blank" rel="noreferrer">View live</a>');if(p.repoUrl)links.push('<a class="btn btn-ghost" href="'+p.repoUrl+'" target="_blank" rel="noreferrer">View code</a>');links.push('<a class="btn btn-ghost" href="#contact">Hire for something similar</a>');document.getElementById("m-links").innerHTML=links.join("");modal.hidden=false}
document.querySelectorAll(".tab").forEach(tab=>{tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("is-on"));tab.classList.add("is-on");filter=tab.dataset.filter;render()})});
grid.addEventListener("click",e=>{const card=e.target.closest("[data-id]");if(card)openProject(card.dataset.id)});
document.getElementById("close").addEventListener("click",()=>{modal.hidden=true});
modal.addEventListener("click",e=>{if(e.target===modal)modal.hidden=true});
menu.addEventListener("click",()=>{menu.classList.toggle("active");navLinks.classList.toggle("open")});
navLinks.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menu.classList.remove("active");navLinks.classList.remove("open")}));
function showSent(){const contact=document.getElementById("contact");const y=contact.getBoundingClientRect().top+window.scrollY-8;window.scrollTo(0,Math.max(0,y));}
document.getElementById("form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,btn=document.getElementById("submitBtn"),msg=document.getElementById("form-msg"),done=document.getElementById("form-success");if(document.activeElement)document.activeElement.blur();btn.disabled=true;btn.textContent="Sending...";msg.hidden=true;try{const res=await fetch("https://api.web3forms.com/submit",{method:"POST",body:new FormData(form)});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false)throw new Error("fail");form.reset();form.hidden=true;done.hidden=false;showSent();requestAnimationFrame(showSent);setTimeout(showSent,60)}catch{msg.hidden=false;msg.textContent="Could not send. Use WhatsApp instead.";btn.disabled=false;btn.textContent="Send message"}});
document.addEventListener("DOMContentLoaded",()=>{if(window.AOS)AOS.init({duration:500,offset:40,easing:"ease-out",once:true});render()});
