const projects=[{id:"electrohub",title:"ElectroHub",category:"fullstack",status:"Live",image:"https://raw.githubusercontent.com/osascodes/benjamin-portfolio/main/images/benjamin-electrohub-mockup.png",summary:"A demo electronics store with product browsing, cart, and a full checkout flow.",problem:"Needed a real storefront — not a static catalog — to show product pages, cart logic, and a checkout path clients can understand.",role:"Built and customized the storefront, catalog, cart, and checkout experience.",outcome:"A working WooCommerce store used as a reference for e-commerce builds.",stack:["WordPress","WooCommerce","Elementor","CSS","JavaScript"],liveUrl:"https://shop.osastech.com.ng",repoUrl:"https://github.com/osascodes/wp-custom-scripts"},{id:"pixelpulse",title:"PixelPulse",category:"frontend",status:"In progress",image:"https://raw.githubusercontent.com/osascodes/benjamin-portfolio/main/images/benjamin-pixelpulse-mockup.png",summary:"A modern business website concept for presenting services with a sharper brand layout.",problem:"Most service sites bury the offer under filler copy and weak structure.",role:"Frontend architecture, layout system, and page structure.",outcome:"A reusable marketing shell with clear sections for services, work, and contact.",stack:["Next.js","React","Tailwind CSS","JavaScript"]},{id:"skycast",title:"SkyCast",category:"frontend",status:"In progress",image:"https://raw.githubusercontent.com/osascodes/benjamin-portfolio/main/images/benjamin-skycast-mockup.png",summary:"A responsive weather app that pulls live data and swaps icons by condition.",problem:"A small product brief: take a public API and turn it into a usable interface on mobile.",role:"UI, API integration, and responsive states.",outcome:"A clean weather client using the OpenWeather API with condition-based visuals.",stack:["HTML","CSS","JavaScript","Fetch API"]}];
const grid=document.getElementById("grid");const count=document.getElementById("count");const modal=document.getElementById("modal");const menu=document.getElementById("menu");const navLinks=document.getElementById("nav-links");let filter="all";const dirs=["fade-up","fade-down","fade-left","fade-right"];
function list(){return filter==="all"?projects:projects.filter(p=>p.category===filter)}
function render(){const items=list();count.textContent=items.length+(items.length===1?" project":" projects");grid.innerHTML=items.map((p,i)=>'<button class="card" data-id="'+p.id+'" data-aos="'+dirs[i%dirs.length]+'"><div class="thumb"><img src="'+p.image+'" alt="'+p.title+' preview"><span class="badge">'+(p.category==="fullstack"?"Full stack":"Frontend")+'</span></div><div class="card-body"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h3>'+p.title+'</h3><span class="status">'+p.status+'</span></div><p>'+p.summary+'</p><p class="more">View project →</p></div></button>').join("");if(window.AOS)AOS.refresh()}
function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;document.getElementById("m-tag").textContent=(p.category==="fullstack"?"Full stack":"Frontend")+" · "+p.status;document.getElementById("m-title").textContent=p.title;document.getElementById("m-summary").textContent=p.summary;document.getElementById("m-problem").textContent=p.problem;document.getElementById("m-role").textContent=p.role;document.getElementById("m-outcome").textContent=p.outcome;document.getElementById("m-stack").innerHTML=p.stack.map(s=>"<span>"+s+"</span>").join("");const img=document.getElementById("m-image");img.src=p.image;img.alt=p.title;img.hidden=false;const links=[];if(p.liveUrl)links.push('<a class="btn btn-solid" href="'+p.liveUrl+'" target="_blank" rel="noreferrer">View live</a>');if(p.repoUrl)links.push('<a class="btn btn-ghost" href="'+p.repoUrl+'" target="_blank" rel="noreferrer">View code</a>');links.push('<a class="btn btn-ghost" href="#contact">Hire for something similar</a>');document.getElementById("m-links").innerHTML=links.join("");modal.hidden=false}
document.querySelectorAll(".tab").forEach(tab=>{tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("is-on"));tab.classList.add("is-on");filter=tab.dataset.filter;render()})});
grid.addEventListener("click",e=>{const card=e.target.closest("[data-id]");if(card)openProject(card.dataset.id)});
document.getElementById("close").addEventListener("click",()=>{modal.hidden=true});
modal.addEventListener("click",e=>{if(e.target===modal)modal.hidden=true});
menu.addEventListener("click",()=>{menu.classList.toggle("active");navLinks.classList.toggle("open")});
navLinks.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menu.classList.remove("active");navLinks.classList.remove("open")}));
document.getElementById("form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,btn=document.getElementById("submitBtn"),msg=document.getElementById("form-msg");btn.disabled=true;btn.textContent="Sending...";msg.hidden=true;try{const res=await fetch("https://api.web3forms.com/submit",{method:"POST",body:new FormData(form)});if(!res.ok)throw new Error("fail");form.reset();msg.hidden=false;msg.textContent="Sent."}catch{msg.hidden=false;msg.textContent="Could not send. Use WhatsApp instead."}btn.disabled=false;btn.textContent="Send message"});
document.addEventListener("DOMContentLoaded",()=>{if(window.AOS)AOS.init({duration:900,offset:80,easing:"ease-out",once:true});render()});
